### ISSUE TITLE
Timing bug with Suspense render results in `TypeError: Cannot set property '0' of null.`

### ISSUE THREAD

**Issue by msluther** [preactjs/preact#2488]
The app crash I'm seeing originates from [here](https://github.com/preactjs/preact/blob/master/compat/src/suspense.js#L101) and surfaced as `TypeError: Cannot set property '0' of null.`

This was discovered during an application reworking to use `preact` rather than `react`.  The bug does not repro with `react`.

### Reproduction

CodeSandbox available [here](https://codesandbox.io/s/quiet-brook-hk9e1?file=/src/index.js)
Minimal repo showing the issue is available [here](https://github.com/msluther/preact-suspense-timing-bug)

### Steps to reproduce

Force a re-render of a component hosting the `<Suspense />` element before the initial fallback has rendered.  In the minimal repro and my case, this was happening because something was being calculated and put into state during `componentDidMount`.

`Suspense` thinks it needs to render the fallback and detach the `lazy` component, however, because of the external re-render, there are no children in the `vnode`

### Expected Behavior

Either the `lazy` is rerun, or the fallback is rendered.

### Actual Behavior

The app crashes with `TypeError: Cannot set property '0' of null.`

**Comment by duxiaofeng-github** [comment]
same here, i'm using lazy route in my app too.

i output some debug message via console and i found out this error message was threw by preact compat, when it is loading lazy route.

but i can't find where the bug is exactly.

**Comment by duxiaofeng-github** [comment]
according to #2519 , i downgrade preact to 10.0.5 and this bug is gone.

**Comment by VitaliiPyvovar** [comment]
It is broken on version 10.5.7

**Comment by marvinhagemeister** [comment]
@VitaliiPyvovar what is broken? Can you file a new issue for that? We'd love to take a look at it, but we need more information than "something is broken".

**Comment by iMakedonsky** [comment]
Suspense causes following error on preact 10.5.12:
`Cannot set property __h of null;`

While on latest 16.x react, everything works fine.

I used webpack aliases from docs.

This happens when I focus into this component in project running  on create-react-app+craco+typescript.

**Comment by rdalmas** [comment]
@iMakedonsky I fixed after lazy loading the module encapsulated within the Suspense. Have you tried that?

**Comment by iMakedonsky** [comment]
@rdalmas there were a couple of issues with suspense.
1) multiple lazy children inside suspense with `preact/compat` is causing one such bug. Fixed by wrapping only one lazy child inside a Suspense.
2) There is a problem with components triggering onClick callbacks after being unmounted. Fixed by:
```
import { options } from 'preact';
options.debounceRendering = setTimeout;
```
3) There are hydrate issues if you're using ssr/prerendering. Resolved by using `preact-iso.lazy/hydrate` instead of regular `lazy/hydrate`

**Comment by rdalmas** [comment]
@iMakedonsky You saved me hours of debugging with the #2. Thanks!

**Comment by imgalli** [comment]
Hi, is it likely that there'll be any progress on this? Am currently reverting to `10.5.4`.

I can see there was a PR but this was closed? https://github.com/preactjs/preact/pull/3128

**Comment by davidrhoderick** [comment]
This shouldn't be closed (or maybe a new issue should be made) because as of `10.5.14`, I get a `t.__H is null` error.  When I downgrade to `10.5.4` as per @imgalli suggests, it goes away.

**Comment by tony-scio** [comment]
This issue still exists in `10.8.2`. I can't get anything later than `10.5.4` to work.
