### ISSUE TITLE
Posible memory leak  

### ISSUE THREAD

**Issue by Z2Y** [preactjs/preact#3668]
**Describe the bug**
When i use preact with a virtualized list, I found memroy not gabage collected. this may cased by a chrome issue:
The MouseEventManager keeps removed DOM nodes alive until subsequent click   https://bugs.chromium.org/p/chromium/issues/detail?id=1177010
if there is no click event for a while , (such as scrolling infinite card list ), the memory usage grows  until next click.

**Comment by marvinhagemeister** [comment]
Please share more information about your setup. We cannot see your screen and don't know what your code looks like, so it's pretty much impossible to help with the issue you're seeing. Specifically the virtual list implementation that's used in your project and how you're using it might be of interest.

**Comment by Z2Y** [comment]
<img width="772" alt="1660469565(1)" src="https://user-images.githubusercontent.com/68933742/184531182-9afd68db-075f-47ba-9ba0-812a64829c24.png">

the event handler hold the ref of a unmountd vnode, ant the vnode hold the parent vnode. if the detached dom not gabage collected , it will cause memory leak.

**Comment by JoviDeCroock** [comment]
From the linked issue this is a chrome bug and not a Preact one, there's not much we can do about the implementation of a browser event handler as this would occur in any library. The screenshot attached also does not seem to relate to the bug as this is a VDOM structure.

The event-handler in question is a native one as we aren't creating our own events so the only things interacting here should be your callback and the browser event-handler.

**Comment by Z2Y** [comment]
I managed to create a demo to reproduce it  https://codesandbox.io/s/preact-vlist-demo-ehphz9
steps: Add some items and then scroll up and down, As the chrome devetool show , the number of detached HtmlButtonElement grows up.
<img width="1380" alt="WeChat0a55e3857971618997c10743f53c67a5" src="https://user-images.githubusercontent.com/68933742/184571304-f1fcff54-6331-4456-9dcf-92bfb9bdea21.png">

**Comment by developit** [comment]
@Z2Y this happens because `SomeButtonItem` closes over `props.children`, which retains it. The issue is already fixed in Preact 11, where `props.children` is a pure JSX element with no tree structure:
https://codesandbox.io/s/preact-vlist-demo-forked-o26dg7?file=/src/index.js

In the meantime, here's a workaround that adds some additional unmount cleanup that likely addresses the issue:

```js
import { options } from 'preact';

let oldUnmount = options.unmount;
options.unmount = (vnode) => {
    if (oldUnmount) oldUnmount(vnode);
    if (vnode.__e) vnode.__e.l = undefined;
    if (vnode.__c) vnode.__c.__H = undefined;
    vnode.__ = vnode.__k = vnode.props = undefined;
};
```

**Comment by Z2Y** [comment]
@developit Dose the workaround has other side effects？ Since there are some work after options.unmount.
https://github.com/preactjs/preact/blob/1cb4b3811599095ea64710faaa260350a1bc7c5b/src/diff/index.js#L499-L527

Currently I add these vnode to a set then do the cleanup later.
```javascript
options.unmount = (vnode) => {
    if (oldUnmount) oldUnmount(vnode);
    unmountedVnodes.add(vnode); // then do cleanup in a setInterval
};
```

**Comment by developit** [comment]
@Z2Y the workaround won't break anything, I only have it clearing properties that Preact ignores during unmounting.

Your Set solution is good though, you could iterate over the properties of each and set them to undefined.

**Comment by JoviDeCroock** [comment]
@developit that workaround might be dangerous in suspense scenario's no?

**Comment by Z2Y** [comment]
I upgrade to latest preact v10.11.0, but the problem still exist.

**Comment by JoviDeCroock** [comment]
@shakyShane this might be a totally different issue, mind reproducing it for us so we can see what exactly is holding onto DOM-nodes

**Comment by shakyShane** [comment]
@JoviDeCroock I realised this pattern causes the same problem in React too. I often use the pattern of waiting for an element to finish transitioning, before unmounting.

Here's a vid showing the detached dom nodes: 

https://github.com/user-attachments/assets/6ee54293-4ca3-4b0a-921e-d2af82aa3258

And the code/site.

code: https://github.com/shakyShane/preact-memory/blob/main/src/preact.js#L20
deployed: https://elaborate-cuchufli-64afa2.netlify.app/preact

Love to know if you have any thoughts/ideas - it's clearly something related to event handlers.

**Comment by JoviDeCroock** [comment]
@shakyShane the events are never detached so the closure stays alive. The closure has a pointer to a property and so on

**Comment by shakyShane** [comment]
I've tried all sorts of variations on this, the only thing that works is the second half the vid, where you unmount immediately. 

This is a pretty big problem in general, like if the sidebar in question has a deep DOM tree - every unmount causes more and more detached nodes with an ever increasing memory footprint.

If anyone knows how to reproduce my example above without a memory leak, it'd make a great blog post!

**Comment by JoviDeCroock** [comment]
@DracoRunner We know by now 😅 There's no need to keep mentioning issues, we can see 2 items up that you have mentioned this issue... multiple times
